import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <body className={`font-sans`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <main className="relative mx-auto flex h-[100dvh] w-full min-w-[300px] max-w-lg flex-col overflow-scroll bg-background outline outline-2 outline-gray-200">
            {session?.user ? children : <Login />}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

function Login() {
  return (
    <div className="flex h-[100dvh] flex-col items-center justify-center">
      <h1 className="text-3xl font-bold">Welcome to SVK Shop</h1>
      <p className="text-lg">Please log in to continue.</p>
      <Link
        href="/api/auth/signin"
        className="rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
      >
        Sign in
      </Link>
    </div>
  );
}
