import "@/styles/globals.css";

import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";
import Link from "next/link";
import { Suspense } from "react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const dynamic = "force-dynamic";

async function CheckSession({ children }: { children: React.ReactNode }) {
  const session = await getServerAuthSession();

  if (session?.user) {
    return <>{children}</>;
  }

  return <Login />;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider cookies={cookies().toString()}>
          <main className="relative mx-auto flex h-[100dvh] w-full min-w-[300px] max-w-lg flex-col overflow-scroll bg-background outline outline-2 outline-gray-200">
            <Suspense fallback="loading...">
              <CheckSession>{children}</CheckSession>
            </Suspense>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

function Login() {
  return (
    <div className="flex h-[100dvh] flex-col items-center justify-center">
      <h1 className="text-3xl font-bold">Welcome to SVK Shop</h1>
      <p className="text-lg">Please log in to continue.</p>
      <Link
        href="/api/auth/signin"
        className="rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
      >
        Sign in
      </Link>
    </div>
  );
}
